#!/usr/bin/env ruby

# this file auto-generates loaders for hyphenation patterns - to be improved

$loader_dir="../tex/loadhyph"

languages = [
		{
			"code" => "hr",
			"name" => "croatian",
			"synonyms" => [],
		#	"hyphenmin" => [],
			"encoding" => "ec",
			"exceptions" => false,
			"message" => "Croatian Hyphenation Patterns",
		},
		{
			"code" => "mn-cyrl-x-new",
			"name" => "mongolian",
			"synonyms" => [],
			"hyphenmin" => [2,2],
			"encoding" => "t2a",
			"exceptions" => false,
			"message" => "New Mongolian Hyphenation Patterns",
		},		{
			"code" => "nl",
			"name" => "dutch",
			"synonyms" => [],
		#	"hyphenmin" => [],
			"encoding" => "ec",
			"exceptions" => true,
			"message" => "Dutch Hyphenation Patterns",
		},
		# {
		# 	"code" => "sl",
		# 	"name" => "slovenian",
		# 	"synonyms" => ["slovene"],
		# 	"hyphenmin" => [2,2],
		# 	"encoding" => "ec",
		# 	"exceptions" => false,
		# 	"message" => "Slovenian Hyphenation Patterns",
		# },
	]

languages.each do |language|
	File.open("#{$loader_dir}/loadhyph-#{language["code"]}.tex", "w") do |file|
		file.puts("% file autogenerated, see svn://tug.org/texhyphen\n%")
		if language["message"] != nil
			file.puts("\\message{#{language["message"]}}\n%")
		end
		
		# TODO:
		# \lefthyphenmin=2 \righthyphenmin=2
		# but probably this needs to reside outside of \begingroup/endgroup
		file.puts('\begingroup')
		file.puts('\catcode`\@=11')
		file.puts('\ifx\@@input\undefined \let\@@input=\input \fi')
		file.puts('\@@input pattern-loader.tex')
		file.puts("\\loadhyphpatterns{#{language["code"]}}{#{language["encoding"]}}%")
		file.puts('\endgroup')
	end
end
