#!/usr/bin/env ruby

# this file auto-generates loaders for hyphenation patterns - to be improved

$loader_dir="../tex/loadhyph"

languages = [
		{
			"code" => "gl",
			"name" => "galician",
			"synonyms" => [],
		#	"hyphenmin" => [],
			"encoding" => "ec",
			"exceptions" => false,
			"message" => "Galician Hyphenation Patterns",
		},
		{
			"code" => "hr",
			"name" => "croatian",
			"synonyms" => [],
		#	"hyphenmin" => [],
			"encoding" => "ec",
			"exceptions" => false,
			"message" => "Croatian Hyphenation Patterns",
		},
		{
			"code" => "hu",
			"name" => "hungarian",
			"synonyms" => [],
		#	"hyphenmin" => [],
			"encoding" => "ec",
			"exceptions" => false,
			"message" => "Hungarian Hyphenation Patterns v20031107",
		},
		{
			"code" => "is",
			"name" => "icelandic",
			"synonyms" => [],
		#	"hyphenmin" => [],
			"encoding" => "ec",
			"exceptions" => false,
			"message" => "Icelandic Hyphenation Patterns",
		},
		{
			"code" => "mn-cyrl-x-new",
			"name" => "mongolian",
			"synonyms" => [],
			"hyphenmin" => [2,2],
			"encoding" => "t2a",
			"exceptions" => false,
			"message" => "New Mongolian Hyphenation Patterns",
		},
		{
			"code" => "nl",
			"name" => "dutch",
			"synonyms" => [],
		#	"hyphenmin" => [],
			"encoding" => "ec",
			"exceptions" => true,
			"message" => "Dutch Hyphenation Patterns",
		},
		{
			"code" => "ro",
			"name" => "romanian",
			"synonyms" => [],
			"hyphenmin" => [2,2],
			"encoding" => "ec",
			"exceptions" => false,
			"message" => "Romanian Hyphenation Patterns", # : `rohyphen' 1.1 <29.10.1996>
		},
		{
			"code" => "hsb",
			"name" => "uppersorbian",
			"synonyms" => [],
			"hyphenmin" => [2,2],
			"encoding" => "ec",
			"exceptions" => true,
			"message" => "Hyphenation patterns for Upper Sorbian, E. Werner",
		#	\message{Hyphenation patterns for Upper Sorbian, E. Werner}
		#	\message{Completely new revision 1997, March 22}
		},
		{
			"code" => "zh-latn",
			"name" => "pinyin",
			"synonyms" => [],
			"hyphenmin" => [1,1],
			"encoding" => "ec",
			"exceptions" => false,
			"message" => "Hyphenation patterns for unaccented pinyin syllables (CJK 4.8.0)",
		},
		{
			"code" => "ia",
			"name" => "interlingua",
			"synonyms" => [],
		#	"hyphenmin" => [],
			"encoding" => "ascii",
			"exceptions" => false,
			"message" => "Hyphenation Patterns for Interlingua",
		},
	# {
		# 	"code" => "sl",
		# 	"name" => "slovenian",
		# 	"synonyms" => ["slovene"],
		# 	"hyphenmin" => [2,2],
		# 	"encoding" => "ec",
		# 	"exceptions" => false,
		# 	"message" => "Slovenian Hyphenation Patterns",
		# },
	]
	
	# Loading CZ hyphenation patterns: Pavel Sevecek, v3, 1995

languages.each do |language|
	File.open("#{$loader_dir}/loadhyph-#{language["code"]}.tex", "w") do |file|
		file.puts("% file autogenerated, see svn://tug.org/texhyphen\n%")
		if language["message"] != nil
			file.puts("\\message{#{language["message"]}}\n%")
		end
		
		# TODO:
		# \lefthyphenmin=2 \righthyphenmin=2
		# but probably this needs to reside outside of \begingroup/endgroup
		file.puts('\begingroup')
		file.puts('\catcode`\@=11')
		file.puts('\ifx\@@input\undefined \let\@@input=\input \fi')
		file.puts('\@@input pattern-loader.tex')
		file.puts("\\loadhyphpatterns{#{language["code"]}}{#{language["encoding"]}}%")
		file.puts('\endgroup')
	end
end
